"""Playbook library: HOW each primary NBA is executed. One row per playbook."""
import pandas as pd

PLAYBOOKS = [
    dict(playbook_id="PB01_RETENTION", primary_nba="Retention Conversation",
         objective="Understand why commercially important spend is falling and stabilise it. Do not push product usage by default.",
         owner_role="Account Manager (broker-led) / Customer Success / Growth (self-serve)", delivery_mode="Human",
         recommended_channel="Personal email to arrange a call, then call",
         first_action="Read the internal brief, then send the outreach draft to book a 20-minute conversation.",
         follow_up_days=7,
         cadence="Outreach day 0; one follow-up day 7; conversation; recovery plan review day 30; GMV check day 90.",
         conversation_themes="Stock availability; price competitiveness; assortment / fit; purchase cadence; competitor or offline wholesaler use; operational friction (delivery, quality, payment); share of wallet with Fleek.",
         success_condition="Root cause logged and next-90-day GMV back to at least the Sep-Nov (H1) level, or the decline arrested.",
         stop_condition="Customer confirms a planned pause/seasonal gap (log cadence), or no response after 2 attempts (escalate).",
         escalation_condition="No response after 2 attempts, or Key account with further decline -> Portfolio Lead.",
         next_rerun="Stay in playbook while momentum is Declining; exit when momentum is Stable/Growing for a full run; if the account lapses, NBA moves to Verify/Win-Back.",
         notes="Never recommend more chat/video/browsing/offers as the fix. Self-Serve accounts have no AM: assign a named CS/Growth owner."),
    dict(playbook_id="PB02_VERIFY_WINBACK", primary_nba="Verify Demand / Win-Back",
         objective="Separate real churn from infrequent buying; recover established buyers.",
         owner_role="Account Manager / Customer Success / Growth", delivery_mode="Human",
         recommended_channel="Personal email, then call if they reply",
         first_action="Established buyer: win-back conversation. One-off / thin history or recent inactivity: cadence check-in first. Do not assume churn.",
         follow_up_days=14,
         cadence="Check-in day 0; one follow-up day 14; record cadence or outcome.",
         conversation_themes="Usual buying frequency (seasonal, project-based, ongoing); upcoming needs; anything that stopped them buying.",
         success_condition="Cadence recorded and account reclassified, or a new order within 90 days (60 days for recent-inactivity checks).",
         stop_condition="Customer confirms infrequent/seasonal buying (set a reminder for their window) or confirms churn (log reason).",
         escalation_condition="Key account with no response after 2 attempts -> Portfolio Lead.",
         next_rerun="If an order appears, the account re-segments automatically; if confirmed seasonal, suppress re-contact until the stated window.",
         notes="Never say 'you churned' or 'you've stopped buying'. Growth nudges stay blocked until the check is complete."),
    dict(playbook_id="PB03_GUIDED_MIGRATION", primary_nba="Guided Self-Serve Migration",
         objective="Teach the customer to discover and buy stock independently while keeping AM support available.",
         owner_role="Account Manager (Portfolio Lead sign-off for Key)", delivery_mode="Hybrid",
         recommended_channel="AM call + in-app walkthrough; automated milestone tracking",
         first_action="Phase 1 Ready: Day 0 walkthrough call. Manual Review: resolve the guardrail first. Key: obtain sign-off first. Pre-entry: encourage a second self-serve checkout.",
         follow_up_days=15,
         cadence="Day 0 intro/walkthrough; Day 15-30 light check-in (PDP views, app use, offers, any self-serve order); Day 45 formal review (M1-M4 + GMV guardrail); Day 90 outcome review.",
         conversation_themes="Finding relevant stock independently; browsing regularly; shortlisting where supported; Make an Offer where appropriate; self-serve checkout. AM support stays in place.",
         success_condition="Day 90: Self-Serve Capability Demonstrated (>=25 PDP views, >=6 app days, self-serve share above baseline) with GMV guardrail held.",
         stop_condition="GMV guardrail breached (At Risk) -> restore high-touch support; no behaviour change at day 90 -> reassess suitability.",
         escalation_condition="At Risk at day 45; any Key account change; customer pushback on the change.",
         next_rerun="Enter 90-day monitoring inputs; migration_progress_status updates (Baseline/Progressing/Capability/At Risk). Day-90 outcomes: Capability Demonstrated, Progressing - Extend, At Risk - Restore support, No Change - Reassess.",
         notes="Frame around faster access, browsing anytime, direct control and flexibility. Never mention Fleek cost reduction or 'migration'."),
    dict(playbook_id="PB04_ESTABLISH", primary_nba="Establish / Re-establish",
         objective="Create (new) or rebuild (returned) a repeatable buying pattern.",
         owner_role="Automation (new) / Account Manager or CS (returned Key/Core)", delivery_mode="Automated (new) / Human (returned)",
         recommended_channel="New: email / in-app onboarding. Returned: personal email then call.",
         first_action="New: send onboarding message. Returned: welcome-back outreach to understand what brought them back.",
         follow_up_days=14,
         cadence="New: day 0 message, day 14 follow-up only if no second order. Returned: day 0 outreach, day 10 follow-up.",
         conversation_themes="Returned: what brought them back; what they are sourcing now; how often they plan to buy.",
         success_condition="New: 2+ orders across 2+ months within 90 days. Returned: orders in at least 2 of the next 3 months.",
         stop_condition="Second order placed (new) or cadence agreed (returned).",
         escalation_condition="Returned Key account with no response after 2 attempts -> Portfolio Lead.",
         next_rerun="Once H1/H2 history exists the account leaves this playbook automatically via re-segmentation.",
         notes="Do not treat returned customers as brand-new."),
    dict(playbook_id="PB05_DISCOVERY_TO_OFFER", primary_nba="Discovery-to-Offer Enablement",
         objective="Help an independently browsing customer turn browsing into negotiation and purchase.",
         owner_role="Automation", delivery_mode="Automated",
         recommended_channel="Email / in-app message",
         first_action="Send one educational Make an Offer prompt.",
         follow_up_days=14,
         cadence="One nudge; one follow-up at day 14 only if still browsing with <3 offers; then stop.",
         conversation_themes="",
         success_condition="3+ offers within 90 days and ideally an order afterwards (association only - no offer-acceptance data).",
         stop_condition="Offers reach 3, or two messages sent, or account becomes inactive/declining.",
         escalation_condition="None (automated). Re-routes automatically if momentum turns Declining/Lapsed.",
         next_rerun="No re-send while the action is already logged for this NBA; eligible again only after the NBA changes.",
         notes="No GMV floor: marginal cost is low and priority already controls importance."),
    dict(playbook_id="PB06_REINFORCE", primary_nba="Reinforce Successful Behaviour",
         objective="Keep strong self-servers buying without inventing a feature gap.",
         owner_role="Automation", delivery_mode="Automated",
         recommended_channel="Email / in-app message",
         first_action="Send one light reinforcement / stock-discovery reminder.",
         follow_up_days=30,
         cadence="One message per 30 days at most.",
         conversation_themes="",
         success_condition="GMV run-rate maintained or higher, with GMV in each month of the next quarter.",
         stop_condition="Account shows Recent Inactivity (playbook must not run) or momentum turns Declining.",
         escalation_condition="Recent Inactivity -> Verify check (human).",
         next_rerun="Suppressed if Recent Inactivity; otherwise no repeat inside 30 days.",
         notes="Do not tell healthy users to 'use feature X'. AM-owned accounts: notify the AM before sending."),
    dict(playbook_id="PB07_SERVICE_MODEL_REVIEW", primary_nba="Service Model Review",
         objective="Decide whether AM/broker effort is justified for a low-value, broker-dependent account.",
         owner_role="Portfolio Lead", delivery_mode="Human (internal only)",
         recommended_channel="Internal review - no customer contact",
         first_action="Review the account card and choose: maintain support / move to lower-touch / automated nurture / revisit later.",
         follow_up_days=14,
         cadence="Decision within 14 days; revisit next quarter.",
         conversation_themes="",
         success_condition="Decision logged; broker effort reduced where agreed without GMV loss.",
         stop_condition="Decision recorded.",
         escalation_condition="None.",
         next_rerun="Decision stored; account not re-queued unless its NBA changes.",
         notes="No ROI calculation (AM cost data unavailable). No customer message is generated."),
    dict(playbook_id="PB08_NURTURE", primary_nba="Automated Nurture",
         objective="Low-cost engagement across the long tail, tailored by nurture sub-context.",
         owner_role="Automation", delivery_mode="Automated",
         recommended_channel="Email / in-app message",
         first_action="Send the sub-context message (dormant, new, returned, repeat, engaged-not-converting, standard, rising-tail early).",
         follow_up_days=30,
         cadence="Dormant: one message per 60 days. Others: one per 30 days. Never on every rerun.",
         conversation_themes="",
         success_condition="Any (repeat) order within 90 days.",
         stop_condition="Order placed, unsubscribe, or 2 unanswered dormant messages (pause 6 months).",
         escalation_condition="Rising Tail accounts that cross the Core line re-route automatically.",
         next_rerun="No repeat send while the logged action is inside its cadence window.",
         notes="Engaged-not-converting: conversion prompt, not 'browse more'."),
    dict(playbook_id="PB09_RANGE_TEST", primary_nba="Range Expansion Test (secondary)",
         objective="Experiment: will a healthy single-product-type self-server try the other product type?",
         owner_role="Automation (experiment owner: Growth)", delivery_mode="Automated experiment",
         recommended_channel="Email / in-app message (treatment arm only)",
         first_action="Deterministic 50/50 assignment by account_id hash; message treatment arm only; holdout receives nothing.",
         follow_up_days=30,
         cadence="Single message; read-out after 90 days treatment vs holdout.",
         conversation_themes="",
         success_condition="Share of accounts placing an order of the other product type, treatment vs holdout; GMV not lower than holdout.",
         stop_condition="Single message only.",
         escalation_condition="None.",
         next_rerun="Arm assignment is stable across reruns (hash of account_id).",
         notes="Experimental. Never claim a commercial benefit. Current eligible sample (2) is far too small for a read-out."),
]


def playbook_library() -> pd.DataFrame:
    return pd.DataFrame(PLAYBOOKS)


NBA_TO_PLAYBOOK = {p["primary_nba"]: p["playbook_id"] for p in PLAYBOOKS}
